### ISSUE TITLE
Read wasm instead of wtns

### ISSUE THREAD

**Issue by valavanisleonidas** [iden3/react-native-rapidsnark#1]
Hello, 

First of all, great work.

In the example i see you load wtns file and read using RNFS. I want to load the wasm and calculate the witness bins in react native. I have seen this [link](https://github.com/cawfree/react-native-webassembly) that loads the webAssembly and then this [link](https://github.com/0xPolygonID/js-sdk-react-native-tools/tree/develop) that does the witness calculation but for some reason the witness calculation crashes. I was wondering if you tried that and have an example ?

I would appreciate it.

**Comment by demonsh** [comment]
Hi @valavanisleonidas in this library we definitely will not read wasm.
First of all this library it is just pure prover. How witness will be calculated it is up to the application. 
Depends on the application witness can be calculated by wasm inside app or in WebView or by C++ code.
Later we will add tutorial how you can compile C++ witness generated by circom for mobile platforms.

I calculated witness with all 3 method and all 3 are valid way to generate witness.

- For C++ version you can use this as a reference https://github.com/0xPolygonID/witnesscalc
- "react-native-webassembly" worked for me for witness generation at least we had some tests that run with it. Unfortunately I don't have any working examples at the moment, but just can confirm that it worked for me. 
- For WebView version you can use [snarkjs](https://github.com/iden3/snarkjs)

My personal preference is C++ if you have build in circuit in you application and WebView if you have dynamic circuits. 
For dynamic case I'm not sure that Apple will allow publish application if you execute wasm natively. But if you have static linked wasm then I don't see reasone do not use C++ version and adding havy wasm execution runtime to the application.

**Comment by valavanisleonidas** [comment]
thank you @demonsh for the answer. the project was on hold thats why responded late. 

for the webview do you have an example using react-native-webview to run snarkjs? I was trying but wasn't able to run it successfully. if not the c++ tutorials would be awesome!

**Comment by demonsh** [comment]
Hi @valavanisleonidas
I plan to do both for C++ version and for web-view.
Also we plan separate lib for witness calculation from wtns files.
