### ISSUE TITLE
Windows + Android error

### ISSUE THREAD

**Issue by ahache** [iden3/react-native-rapidsnark#13]
Hi guys, have been trying to get a simple demo setup locally and keep running into the same issue. I'm using Windows, testing on android device + emulator and have tried using Expo development build as well as just RN. 

The error is `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNRapidsnark' could not be found. Verify that a module by this name is registered in the native binary.`

**Comment by 5eeman** [comment]
Hi!
Please consider using branch `release/0.0.1-alpha.6`
I'm currently looking into this issue and trying to reproduce.
I'll push additional expo example once I'll get success scenario.

**Comment by 5eeman** [comment]
I've added working example for Expo in separate branch - `expo_example`.
You can find subfolder expo_example.
Works for both Android and iOS sim for me.

**Comment by ahache** [comment]
Tried a fresh setup using `release/0.0.1-alpha.6` branch and the same error is being triggered, maybe a Windows issue. This is true for a new expo build and also the original example in the repo.

Few things I'm having to do after first build fails (and android folder is generated) that could offer some clues:

- Adjusting minSdk version from 23 to 24 in `build.gradle`
- Setting `newArchEnabled=true` in `gradle.properties`

Also just curious about the `expo_example` you included, it looks like a submodule but only seeing a commit hash included. Sorry if I'm missing something basic.

**Comment by ahache** [comment]
Added you to a repo showing the full installation and setup in case that helps

**Comment by 5eeman** [comment]
By reviewing your example I can say two things:
1. Example app fails with or without react-native-rapidsnark. I've created a branch that demonstrates that.
2. Please drop Expo Go - it doesn't support lot of things like linking native modules(or support is tricky and limited idk). Please use pure Expo (development builds instead of loading JS into Expo Go app) or pure React Native.

**Comment by ahache** [comment]
Apologies, the file references were just fixed.

Have been using Expo development builds, building locally and tried EAS.

**Comment by ahache** [comment]
Wanted to update that I managed to get it to work by changing `RNRapidsnark` to `Rapidsnark` in `NativeRapidsnark.ts`
