### ISSUE TITLE
Issues in import and zkey prove

### ISSUE THREAD

**Issue by valavanisleonidas** [iden3/react-native-rapidsnark#4]
Hey guys 

First of all awesome work. the new version has more features and is really fast :)

two issues I have so far. I saw in the readme we should import using 

```
import {groth16ProveWithZKeyFilePath} from "react-native-rapidsnark";
```

but when I do I get `Cannot find module 'react-native-rapidsnark' or its corresponding type declarations.ts(2307)` so i use the old way which is 

```
const rapidsnark = NativeModules.Rapidsnark;
```

Also when I call 

```
rapidsnark.groth16ProveWithZKeyFilePath(zkeyPath,witnessCalculationResult); 
```

it crashes with the error `expecting 7 values received 4` and I have to add 3 params to fix 

So my fix is 

```
rapidsnark.groth16ProveWithZKeyFilePath(zkeyPath,witnessCalculationResult,16384, 16384, 256); 
```

The code works fine with my changes but I encountered these issues in the process

**Comment by 5eeman** [comment]
Hey!
Thanks for opening an issue.
I've pushed type declarations to main branch.
Please try using direct dependency on git latest version of main branch for now.

**Comment by 5eeman** [comment]
I'm closing this one for now.
Feel free to reopen or adding comments in case of issues.
