### ISSUE TITLE
How to support New Architecture of RN?

### ISSUE THREAD

**Issue by superbboy-2022** [iden3/react-native-rapidsnark#9]
Hey guys, 

I have been  working on integrating `react-native-rapidsnark` with new architecture of RN for one day, but there is still no progress. Please kindly help. 

## My ENV
- MacOS 13.6.6, Intel 
- Test example: the example included in this repository.  

## First

 I just update the Podfile and add the RCT_NEW_ARCH_ENABLED env, just like this:
```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

ENV['RCT_NEW_ARCH_ENABLED'] = "1"
use_frameworks! :linkage => :static
```
And then I update the pods and run it

```shell
yarn pods
yarn ios
```
The app start successfully in IOS simulator,  but when I  click the 'Run prover' , the metro report the following error: 

```
 ERROR  Error proving circuit, code:  undefined , err: The package 'react-native-rapidsnark' doesn't seem to be linked. Make sure:

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo Go

```

## Second 

After read some documents, I update Asp.tsx in the example to  us the TurboModule version: 

```typescript
import RNRapidsnark from '@iden3/react-native-rapidsnark/src/NativeRapidsnark';

const DEFAULT_PROOF_BUFFER_SIZE = 1024;
const DEFAULT_ERROR_BUFFER_SIZE = 256;

  const runGroth16BufferProver = async () => {
    console.log('Calling useGroth16BufferProver');

    const zkeyF = await getZkeyFile();
    const wtnsF = await getWtnsFile();
    console.log('zkeyF: ', zkeyF.length);
    console.log('wtnsF: ', wtnsF.length);

    const startTime = performance.now();
    const publicBufferSize = await RNRapidsnark.groth16PublicSizeForZkeyFile(zkeyPath, DEFAULT_ERROR_BUFFER_SIZE);
    const proverResult = await RNRapidsnark.groth16Prove(zkeyF, wtnsF, DEFAULT_PROOF_BUFFER_SIZE, publicBufferSize, DEFAULT_ERROR_BUFFER_SIZE);
    const diff = performance.now() - startTime;
    setProofExecTime(diff);

    return proverResult;
  };

```
This time, I got the following error: 

```
error: Error: Unable to resolve module /Users/xxxxx/Study/GitHub/iden3/react-native-rapidsnark/src/index/src/NativeRapidsnark from /Users/xxxxx/Study/GitHub/iden3/react-native-rapidsnark/example/src/App.tsx:

None of these files exist:
  * ../src/index/src/NativeRapidsnark(.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * ../src/index/src/NativeRapidsnark/index(.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  10 | // } from '@iden3/react-native-rapidsnark';
  11 |
> 12 | import RNRapidsnark from '@iden3/react-native-rapidsnark/src/NativeRapidsnark';
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  13 |
  14 | const DEFAULT_PROOF_BUFFER_SIZE = 1024;
  15 | const DEFAULT_ERROR_BUFFER_SIZE = 256;
    at ModuleResolver.resolveDependency (/Users/xxxxx/Study/GitHub/iden3/react-native-rapidsnark/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (/Users/xxxxx/Study/GitHub/iden3/react-native-rapidsnark/example/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
```

**Comment by 5eeman** [comment]
Hey!
Checking this one

**Comment by 5eeman** [comment]
Please try running `pod install` like this

`RCT_NEW_ARCH_ENABLED=1 pod install` in `ios` folder

**Comment by superbboy-2022** [comment]
Thank you for reply. 

 I have executed the `yarn pods`  after modified the Podfile.  

I also try to execute `RCT_NEW_ARCH_ENABLED=1 pod install` in `ios` folder, and got the same error.

**Comment by 5eeman** [comment]
I've already reproduced this problem and trying to fix it.
Meanwhile please check `example`, cuz using `RNRapidsnark` directly from `'@iden3/react-native-rapidsnark/src/NativeRapidsnark'` is definitely wrong 😅

**Comment by superbboy-2022** [comment]
I have made it work with new architecture in IOS following the example created by create-react-native-library:

- NativeRapidsnark.ts

RNRapidshark should be Rapidshark to match the project settings.

- index.ts

To use the NativeRapidsnark, following the example created by create-react-native-library:

```js
// @ts-expect-error
const isTurboModuleEnabled = global.__turboModuleProxy != null;

const RapidsnarkModule = isTurboModuleEnabled
  ? require('./NativeRapidsnark').default
  : NativeModules.Rapidsnark;

const Rapidsnark = RapidsnarkModule
  ? RapidsnarkModule
  : new Proxy(
      {},
      {
        get() {
          throw new Error(LINKING_ERROR);
        },
      }
    );
```
- Fix variable names to avoid crashing in IOS simulator

I encountered crash in my IOS simulator after fixing last two problem. 
After comparing the code generated by create-react-native-library (it works with new architecture in IOS), I found inconsistencies between the generated code and the implemented code in terms of variable definitions, which led to cannot locate actual methods. 
Therefore, I have modified the variable names to ensure consistency in Rapidshark.mm/NativeRapidshark.ts

Here is my local patch file you can refer to: 
[0001-Fix-not-work-in-ios-with-new-architecture.patch](https://github.com/user-attachments/files/16043892/0001-Fix-not-work-in-ios-with-new-architecture.patch)

**Comment by 5eeman** [comment]
Hey, 
Please try branch `0.0.1-alpha.5`

**Comment by lukachi** [comment]
Hi @5eeman , i'm struggling with the same error, could you publish please `0.0.1-alpha.5`? so i can test it
